# Generated by Django 4.2.6 on 2023-10-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_images/%B/')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('departure', models.DateField(blank=True, null=True, verbose_name="Jo'nash sanasi")),
                ('desctiption', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha malumot")),
                ('class_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paket turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Narxi')),
            ],
        ),
    ]
