# Generated by Django 4.2.6 on 2023-10-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, null=True, verbose_name='1 - Qism')),
                ('body2', models.TextField(blank=True, null=True, verbose_name='2 - Qism')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pictures/%B/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='post_pictures/%B/')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
