# Generated by Django 4.2.6 on 2023-10-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Hozir mavjudmi'),
        ),
    ]
