# Generated by Django 4.2.6 on 2023-10-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_travel_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
