# Generated by Django 4.2.6 on 2023-10-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_travel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism sharif")),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
                ('comment', models.TextField(blank=True, null=True)),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.travel')),
            ],
        ),
    ]
